version: "2"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf-nginx:/etc/nginx/conf.d"
      - "/etc/letsencrypt/archive/grafana.nube-iiot.com/:/etc/ssl/certs"
  kfc:
    image: grafana/grafana
    container_name: kfc
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./conf-grafana-kfc:/etc/grafana"
    
    
